"use client";

import { useEffect, useState } from "react";
import { DashboardCard } from "@/components/eco/DashboardCard";
import { PieChartWidget } from "@/components/dashboard/PieChartWidget";
import { api } from "@/lib/api";
import toast from "react-hot-toast";

interface Earnings {
  today: number;
  weekly: number;
  monthly: number;
  yearly: number;
  lifetime: number;
}

interface Metrics {
  totalCollections: number;
  totalWasteProcessed: number;
  pendingPayouts: number;
  completedPayouts: number;
}

interface RevenueSummary {
  earnings: Earnings;
  metrics: Metrics;
}

interface AnalyticsItem {
  name: string;
  value: number;
  [key: string]: string | number | undefined;
}

export default function RecyclerRevenuePage() {
  const [summary, setSummary] = useState<RevenueSummary | null>(null);
  const [analytics, setAnalytics] = useState<AnalyticsItem[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchRevenueData = async () => {
      try {
        const [sumRes, anaRes] = await Promise.all([
          api.get("/revenue/summary"),
          api.get("/revenue/analytics"),
        ]);
        
        if (sumRes.data?.success) {
          setSummary(sumRes.data.data);
        }
        if (anaRes.data?.success) {
          setAnalytics(anaRes.data.data);
        }
      } catch {
        toast.error("Failed to load dynamic revenue metrics");
      } finally {
        setLoading(false);
      }
    };
    fetchRevenueData();
  }, []);

  if (loading) {
    return <p>Loading financial parameters...</p>;
  }

  const earnings = summary?.earnings;
  const metrics = summary?.metrics;

  return (
    <div className="space-y-6">
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <DashboardCard title="Monthly Revenue" description="Dynamic calculation from ledger accounts.">
          <p className="text-3xl font-bold">₹{earnings?.monthly.toLocaleString() || "0"}</p>
          <p className="text-xs text-muted-foreground mt-2">
            Today: ₹{earnings?.today.toLocaleString()} · Lifetime: ₹{earnings?.lifetime.toLocaleString()}
          </p>
        </DashboardCard>

        <DashboardCard title="Total Shipments Processed" description="Total confirmed receipt of deliveries.">
          <p className="text-3xl font-bold">{metrics?.totalCollections || "0"}</p>
          <p className="text-xs text-muted-foreground mt-2">
            Total Mass: {metrics?.totalWasteProcessed || "0"} kg
          </p>
        </DashboardCard>

        <DashboardCard title="Payout Status" description="Completed vs Pending disbursements.">
          <p className="text-3xl font-bold">₹{metrics?.completedPayouts.toLocaleString() || "0"}</p>
          <p className="text-xs text-muted-foreground mt-2">
            Pending: ₹{metrics?.pendingPayouts.toLocaleString()}
          </p>
        </DashboardCard>
      </div>

      <div className="grid gap-6 lg:grid-cols-2">
        <DashboardCard title="Financial Performance" description="Breakdown of earnings over time intervals.">
          <div className="space-y-3 pt-2">
            <div className="flex justify-between items-center py-1 border-b">
              <span className="text-sm font-medium">Daily Earnings</span>
              <span className="font-mono text-sm font-semibold">₹{earnings?.today.toLocaleString()}</span>
            </div>
            <div className="flex justify-between items-center py-1 border-b">
              <span className="text-sm font-medium">Weekly Earnings</span>
              <span className="font-mono text-sm font-semibold">₹{earnings?.weekly.toLocaleString()}</span>
            </div>
            <div className="flex justify-between items-center py-1 border-b">
              <span className="text-sm font-medium">Monthly Earnings</span>
              <span className="font-mono text-sm font-semibold text-primary">₹{earnings?.monthly.toLocaleString()}</span>
            </div>
            <div className="flex justify-between items-center py-1 border-b">
              <span className="text-sm font-medium">Yearly Earnings</span>
              <span className="font-mono text-sm font-semibold">₹{earnings?.yearly.toLocaleString()}</span>
            </div>
            <div className="flex justify-between items-center py-1">
              <span className="text-sm font-medium text-muted-foreground">Lifetime Ledger Credits</span>
              <span className="font-mono text-sm font-semibold">₹{earnings?.lifetime.toLocaleString()}</span>
            </div>
          </div>
        </DashboardCard>

        {analytics.length > 0 ? (
          <PieChartWidget
            title="Material Mix Contribution"
            description="Revenues generated by waste category"
            data={analytics}
            dataKey="value"
            nameKey="name"
          />
        ) : (
          <DashboardCard title="Material Mix" description="No material category data available yet." />
        )}
      </div>
    </div>
  );
}
